IOO_AngularJS_ASP_NET_CRUD.web/Controllers/API/BasketElementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using IOO_AngularJS_ASP_NET_CRUD.web.Models;
using IOO_AngularJS_ASP_NET_CRUD.web.Models.DataModels;

namespace IOO_AngularJS_ASP_NET_CRUD.web.Controllers.API
{
    public class BasketElementsController : ApiController
    {

        // GET: api/BasketElements
        public IQueryable<BasketElements> GetBasketElements()
        {
            using (DataContext db = new DataContext())
            {
                return db.BasketElements;
            }
        }

        // GET: api/BasketElements/5
        [ResponseType(typeof(BasketElements))]
        public async Task<IHttpActionResult> GetBasketElements(Guid id)
        {
            using (DataContext db = new DataContext())
            {
                BasketElements basketElements = await db.BasketElements.FindAsync(id);
                if (basketElements == null)
                {
                    return NotFound();
                }

                return Ok(basketElements);
            }
        }
    }
}

IOO_AngularJS_ASP_NET_CRUD.web/Controllers/API/PaymentTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using IOO_AngularJS_ASP_NET_CRUD.web.Models;
using IOO_AngularJS_ASP_NET_CRUD.web.Models.DataModels;

namespace IOO_AngularJS_ASP_NET_CRUD.web.Controllers.API
{
    public class PaymentTypesController : ApiController
    {

        // GET: api/PaymentTypes
        public async Task<IHttpActionResult> GetPaymentTypes()
        {
            using (DataContext dataContext = new DataContext())
            {
                var purchases = await (from p in dataContext.PaymentTypes
                                       where p.InArchive != true
                                       select new
                                       {
                                           p.Id,
                                           p.Name
                                       }).ToListAsync();
                return Ok(purchases);
            }
        }
    }
}

IOO_AngularJS_ASP_NET_CRUD.web/Controllers/API/PurchaseStatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using IOO_AngularJS_ASP_NET_CRUD.web.Models;
using IOO_AngularJS_ASP_NET_CRUD.web.Models.DataModels;

namespace IOO_AngularJS_ASP_NET_CRUD.web.Controllers.API
{
    public class PurchaseStatesController : ApiController
    {
        private DataContext db = new DataContext();

        // GET: api/PurchaseStates
        public IQueryable<PurchaseStates> GetPurchaseStates()
        {
            return db.PurchaseStates;
        }

        // GET: api/PurchaseStates/5
        [ResponseType(typeof(PurchaseStates))]
        public async Task<IHttpActionResult> GetPurchaseStates(int id)
        {
            PurchaseStates purchaseStates = await db.PurchaseStates.FindAsync(id);
            if (purchaseStates == null)
            {
                return NotFound();
            }

            return Ok(purchaseStates);
        }

        // PUT: api/PurchaseStates/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutPurchaseStates(int id, PurchaseStates purchaseStates)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != purchaseStates.Id)
            {
                return BadRequest();
            }

            db.Entry(purchaseStates).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PurchaseStatesExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/PurchaseStates
        [ResponseType(typeof(PurchaseStates))]
        public async Task<IHttpActionResult> PostPurchaseStates(PurchaseStates purchaseStates)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.PurchaseStates.Add(purchaseStates);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = purchaseStates.Id }, purchaseStates);
        }

        // DELETE: api/PurchaseStates/5
        [ResponseType(typeof(PurchaseStates))]
        public async Task<IHttpActionResult> DeletePurchaseStates(int id)
        {
            PurchaseStates purchaseStates = await db.PurchaseStates.FindAsync(id);
            if (purchaseStates == null)
            {
                return NotFound();
            }

            db.PurchaseStates.Remove(purchaseStates);
            await db.SaveChangesAsync();

            return Ok(purchaseStates);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool PurchaseStatesExists(int id)
        {
            return db.PurchaseStates.Count(e => e.Id == id) > 0;
        }
    }
}

IOO_AngularJS_ASP_NET_CRUD.web/Controllers/API/PurchaseTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using IOO_AngularJS_ASP_NET_CRUD.web.Models;
using IOO_AngularJS_ASP_NET_CRUD.web.Models.DataModels;

namespace IOO_AngularJS_ASP_NET_CRUD.web.Controllers.API
{
    public class PurchaseTypesController : ApiController
    {
        private DataContext db = new DataContext();

        // GET: api/PurchaseTypes
        public IQueryable<PurchaseTypes> GetPurchaseTypes()
        {
            return db.PurchaseTypes;
        }

        // GET: api/PurchaseTypes/5
        [ResponseType(typeof(PurchaseTypes))]
        public async Task<IHttpActionResult> GetPurchaseTypes(int id)
        {
            PurchaseTypes purchaseTypes = await db.PurchaseTypes.FindAsync(id);
            if (purchaseTypes == null)
            {
                return NotFound();
            }

            return Ok(purchaseTypes);
        }

        // PUT: api/PurchaseTypes/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutPurchaseTypes(int id, PurchaseTypes purchaseTypes)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != purchaseTypes.Id)
            {
                return BadRequest();
            }

            db.Entry(purchaseTypes).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PurchaseTypesExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/PurchaseTypes
        [ResponseType(typeof(PurchaseTypes))]
        public async Task<IHttpActionResult> PostPurchaseTypes(PurchaseTypes purchaseTypes)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.PurchaseTypes.Add(purchaseTypes);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = purchaseTypes.Id }, purchaseTypes);
        }

        // DELETE: api/PurchaseTypes/5
        [ResponseType(typeof(PurchaseTypes))]
        public async Task<IHttpActionResult> DeletePurchaseTypes(int id)
        {
            PurchaseTypes purchaseTypes = await db.PurchaseTypes.FindAsync(id);
            if (purchaseTypes == null)
            {
                return NotFound();
            }

            db.PurchaseTypes.Remove(purchaseTypes);
            await db.SaveChangesAsync();

            return Ok(purchaseTypes);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool PurchaseTypesExists(int id)
        {
            return db.PurchaseTypes.Count(e => e.Id == id) > 0;
        }
    }
}

IOO_AngularJS_ASP_NET_CRUD.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-dark bg-dark" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Settings
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Product Types", "Index", "ProductTypes")</li>
                            <li>@Html.ActionLink("Products", "Index", "Products")</li>
                            <li>@Html.ActionLink("Payment Types", "Index", "PaymentTypes")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Purchase Types", "Index", "PurchaseTypes")</li>
                            <li>@Html.ActionLink("Purchase States", "Index", "PurchaseStates")</li>
                            <li>@Html.ActionLink("Purchases", "Index", "Purchases")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Basket Elements", "Index", "BasketElements")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>